import Header from "@/components/Header";
import Optimizer from "@/components/Optimizer";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CodeOptimizeHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="flex min-h-screen items-center justify-center !bg-[#bdbbbb]">
          <Optimizer />
        </div>
      </main>
    </>
  );
};

export default Home;
